version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  redis:
    container_name: fastapi-redis
    image: redis:7.2.3
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["bash", "app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
