version: '3.9'

services:

  postgres:
    image: postgres:16.1
    container_name: postgres_school
    restart: always
    ports:
      - $DB_PORT:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school

  redis:
    container_name: redis_school
    image: redis:7.2.4
    env_file:
      - .env
    ports:
      - $REDIS_PORT:6379
    command: redis-server --port $REDIS_PORT --requirepass $REDIS_PASS --maxmemory 250mb
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - school

  backend:
    image:  backend_school_image
    container_name: backend_school
    build: .
    command: [ "bash", "scripts/app.sh" ]
    env_file:
      - .env
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    volumes:
      - ./static/media:/backend_app/static/media
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - school

  # frontend:
  #   container_name: frontend_app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - front_data:/data
  #   networks:
  #     - school

networks:
  school:
    driver: bridge

volumes:
  postgres_data:
  backend_data:
  redis_data:
  # front_data: