version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  # redis:
  #   image: redis:7
  #   container_name: redis_app


  # app:
  #   build:
  #     context: .
  #   env_file:
  #     - .env
  #   container_name: fastapi_app
  #   command: ["bash", "app.sh"]
  #   ports:
  #     - 9999:8000
  #   depends_on:
  #     - postgres
  #     - redis
